name: "Update CHANGELOG.md"
on:
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update changelog
      run: |
        npm install github-release-notes
        export GREN_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        npm run overrideChangelog
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.0
      with:
        commit-message: Update CHANGELOG.md
        title: Update CHANGELOG.md
        body: Update changelog to reflect release changes
        branch: update-changelog
        base: main
